### PR TITLE
Major re-write of Dynu DNS Add On.

### PR DESCRIPTION
**Pull request by vittorio88**
Hello,

I noticed a bug in the recent PR #14  I submitted:
When using jq, and the records are missing (IE domain does not exist), it fails silently, rather than triggering error handling. This can cause quite a few unintended failures and crashes. The fix was to add the missing '-e' flag in the relevant jq commands.

Unfortunataly, it took me several hours to find the bug, and I ended up re-writing the whole add-on in desparation.

Additional benefits:
- Error Handling everywhere
- Code is more modular in separate files
- Main executable is reduced and simplified.

@koying Apologies for the double-work on the validation: I think this final PR has become a pretty solid plug-in now!

Please note, I edited some variable name from in config.json. I recommend deleting the add-on and re-adding it, to make sure the config.json is parsed again. (Rebuild is not sufficient!)

### CODE REVIEW

**Comment by koying** [comment]
Thanks, but at the end of the day that's a new addon, indeed ;)
The simple fact of changing config variable names implies some kind of migration.

Wouldn't it be simpler to just have your own repo with your version?
I don't mind deprecating mine and redirecting to yours. As I said, I don't use dynudns myself.

Alternatively, you could just fix the issue w/o a full rewrite.

Up to you...

**Comment by vittorio88** [comment]
That makes sense, at one point I needed to go at it with a chainsaw, and there was no going back lol. I will move this elsewhere.

**Comment by vittorio88** [comment]
Hello,

I re-wrote the re-write, and made a new addon repo.
https://github.com/vittorio88/addon-ddns-acme

I've modified it further to potentially support other DNS providers such as Duck DNS in the future.

Feel free to close this PR!

Regards,
Vittorio

**Comment by koying** [comment]
Great.
Did you open a dedicated thread on the forum I could redirect to?

**Comment by vittorio88** [comment]
> Great.
> Did you open a dedicated thread on the forum I could redirect to?

No. I'm gonna let it soak a bit for testing before advertising it to others.

I think it's mostly good, but I got my IP temporarily banned from Lets Encrypt for too many requests during testing.

**Comment by vittorio88** [comment]
Hello @koying , I have let it soak, as well as added some new features.
It now supports DuckDNS in addition to DynuDNS.

It is available here:
https://github.com/vittorio88/addon-ddns-acme

The Home Assistant page is here:
https://community.home-assistant.io/t/ddns-acme-add-on/763235

Regards,
Vittorio

**Pull request closed without merging**
